# Generated by Django 5.2.17 on 2026-09-08 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_guestprofile_promotion_booking_status_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('caption', models.CharField(blank=True, max_length=160)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='hotels.hotel')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
